// Данные ресёрча по программам поступления. Правь напрямую, если появляются
// уточнения/новые официальные цифры — приложение читает этот файл при загрузке.
window.APP_DATA = {
  "individualAchievements": {
    "_comment": "Сколько баллов даёт красный аттестат/медаль в каждом вузе. Источник: сводный ресёрч. У тебя есть аттестат с отличием + золотая медаль = засчитывается как максимум по этому пункту в каждом вузе.",
    "ИТМО": { "bonus": 3, "cap": 10 },
    "ВШЭ": { "bonus": 3, "cap": 10 },
    "СПбГУ": { "bonus": 10, "cap": 10 },
    "СПбПУ": { "bonus": 10, "cap": 10 },
    "ЛЭТИ": { "bonus": 10, "cap": 10 },
    "МГТУ им. Баумана": { "bonus": 10, "cap": 10 },
    "СПбГЭУ": { "bonus": null, "cap": null, "note": "не найдено, проверить на abit.unecon.ru" }
  },
  "yourScore": {
    "math": 94,
    "inf": 93,
    "rus": 97,
    "sum": 284
  },
  "programs": [
    {
      "vuz": "ИТМО",
      "faculty": "ФПИиКТ",
      "name": "Программирование и искусственный интеллект",
      "code": "01.03.02",
      "city": "Санкт-Петербург",
      "campus": "Кронверкский пр., 49 · центр",
      "campusFar": false,
      "url": "https://abit.itmo.ru/program/bachelor/ai_programming",
      "urlVerified": false,
      "egeSubjects": "математика + информатика + русский",
      "egeFits": true,
      "needsObsh": false,
      "budget": 144,
      "quota": 72,
      "realEge": 72,
      "budgetOnlyBVI": false,
      "paid": 140,
      "prokhBudget": 295,
      "prokhBudgetApprox": true,
      "prokhBudgetNote": "расхождение источников: моя оценка ≈295, у Gemini заявлено 305 как официальная цифра — ОБЯЗАТЕЛЬНО свериться в конкурсных списках abit.itmo.ru прямо сейчас",
      "priceYear": 649000,
      "filters": ["ai"],
      "starAIDS": 5,
      "starBusiness": 1,
      "profileLabel": "ИИ / программирование",
      "unavailable": false,
      "source": "abit.itmo.ru, 2025, оценка + неподтверждённая цифра Gemini"
    },
    {
      "vuz": "ИТМО",
      "faculty": "ФТИИ",
      "name": "Инженерия искусственного интеллекта",
      "code": "11.03.02",
      "city": "Санкт-Петербург",
      "campus": "Кронверкский пр., 49 · центр",
      "campusFar": false,
      "url": "https://abit.itmo.ru/program/bachelor/aiengineer",
      "urlVerified": true,
      "egeSubjects": "математика + информатика + русский",
      "egeFits": true,
      "needsObsh": false,
      "budget": 32,
      "quota": 10,
      "realEge": 22,
      "paid": 92,
      "prokhBudget": 285,
      "prokhBudgetApprox": true,
      "priceYear": 599000,
      "filters": ["ai"],
      "starAIDS": 5,
      "starBusiness": 1,
      "profileLabel": "ИИ инженерия",
      "unavailable": false,
      "source": "abit.itmo.ru, 2025, оценка"
    },
    {
      "vuz": "ИТМО",
      "faculty": "ФТМИ",
      "name": "Бизнес-информатика и управление на основе данных",
      "code": "38.03.05",
      "city": "Санкт-Петербург",
      "campus": "Кронверкский пр., 49 · центр",
      "campusFar": false,
      "url": "https://ftmi.itmo.ru/ba/technologymanagement",
      "urlVerified": true,
      "egeSubjects": "математика + ОБЩЕСТВОЗНАНИЕ + русский",
      "egeFits": false,
      "needsObsh": true,
      "budget": 55,
      "paid": 64,
      "priceYear": 549000,
      "filters": ["business"],
      "starAIDS": 2,
      "starBusiness": 5,
      "profileLabel": "бизнес+IT",
      "unavailable": true,
      "unavailableReason": "требуется обществознание без альтернативы информатике",
      "source": "ftmi.itmo.ru, 2025"
    },
    {
      "vuz": "СПбГУ",
      "faculty": "ФМКН",
      "name": "Науки о данных",
      "code": "02.03.01",
      "city": "Санкт-Петербург",
      "campus": "Васильевский остров · центр",
      "campusFar": false,
      "url": "https://math-cs.spbu.ru/admission-bsc/",
      "urlVerified": true,
      "egeSubjects": "математика + информатика + русский",
      "egeFits": true,
      "needsObsh": false,
      "minScores": { "math": 80, "inf": 80, "rus": 70 },
      "budget": 30,
      "quota": 27,
      "realEge": 3,
      "budgetOnlyBVI": true,
      "paid": 9,
      "prokhBudget": null,
      "prokhBudgetNote": "бюджет практически весь БВИ, официальный проходной по общему конкурсу не публикуется",
      "prokhPaid": 271,
      "prokhPaidApprox": true,
      "prokhPaidYear": 2024,
      "priceYear": 303800,
      "filters": ["ds", "ai"],
      "starAIDS": 5,
      "starBusiness": 1,
      "profileLabel": "Data Science",
      "unavailable": false,
      "source": "math-cs.spbu.ru, официальный ресёрч в чате, 2025"
    },
    {
      "vuz": "СПбГУ",
      "faculty": "ФМКН",
      "name": "AI360: Математика машинного обучения",
      "code": "02.03.01",
      "city": "Санкт-Петербург",
      "campus": "Васильевский остров · центр",
      "campusFar": false,
      "url": "https://math-cs.spbu.ru/bsc-ai360/",
      "urlVerified": true,
      "egeSubjects": "математика + информатика + русский",
      "egeFits": true,
      "needsObsh": false,
      "minScores": { "math": 80, "inf": 80, "rus": 70 },
      "budget": 30,
      "quota": 28,
      "realEge": 2,
      "budgetOnlyBVI": true,
      "paid": 0,
      "noPaidSeats": true,
      "prokhBudget": null,
      "prokhBudgetNote": "только БВИ / олимпиадники. Gemini заявляет 297 — не подтверждено официально, без диплома олимпиады шансов почти нет",
      "stipend": 40000,
      "creditAvailable": false,
      "priceYear": null,
      "filters": ["ai"],
      "starAIDS": 5,
      "starBusiness": 1,
      "profileLabel": "ML топ-уровень",
      "unavailable": false,
      "source": "math-cs.spbu.ru, 2025"
    },
    {
      "vuz": "СПбГУ",
      "faculty": "ФМКН",
      "name": "Современное программирование",
      "code": "02.03.02",
      "city": "Санкт-Петербург",
      "campus": "Васильевский остров · центр",
      "campusFar": false,
      "url": "https://math-cs.spbu.ru/",
      "urlVerified": false,
      "egeSubjects": "математика + информатика + русский",
      "egeFits": true,
      "needsObsh": false,
      "minScores": { "math": 80, "inf": 80, "rus": 60 },
      "budget": 40,
      "quota": 36,
      "realEge": 4,
      "paid": 9,
      "prokhBudget": 293,
      "prokhBudgetApprox": true,
      "prokhBudgetNote": "цифра из Gemini-отчёта, официально не перепроверена мной напрямую — ЖЁСТКО СВЕРИТЬ",
      "priceYear": 303800,
      "filters": ["it", "ds"],
      "starAIDS": 4,
      "starBusiness": 1,
      "profileLabel": "Программирование",
      "unavailable": false,
      "source": "Gemini-отчёт + math-cs.spbu.ru, 2025, требует проверки"
    },
    {
      "vuz": "СПбГУ",
      "faculty": "Матмех",
      "name": "Прикладная математика, программирование и ИИ",
      "code": "01.03.02",
      "city": "Санкт-Петербург",
      "campus": "Петергоф",
      "campusFar": true,
      "url": "https://spbu.ru/postupayushchim/programms/bakalavriat/prikladnaya-matematika-programmirovanie-i-iskusstvennyy",
      "urlVerified": false,
      "egeSubjects": "математика + информатика + русский",
      "egeFits": true,
      "needsObsh": false,
      "prokhBudget": 263,
      "prokhBudgetApprox": true,
      "priceYear": 290000,
      "filters": ["ai", "ds"],
      "starAIDS": 5,
      "starBusiness": 1,
      "profileLabel": "фундаментальный ИИ",
      "unavailable": false,
      "source": "внутренний ресёрч чата, 2025"
    },
    {
      "vuz": "СПбГУ",
      "faculty": "Экономический факультет",
      "name": "Бизнес-информатика",
      "code": "38.03.05",
      "city": "Санкт-Петербург",
      "campus": "ул. Чайковского · центр",
      "campusFar": false,
      "url": "https://spbu.ru/postupayushchim/programms/bakalavriat/biznes-informatika",
      "urlVerified": true,
      "egeSubjects": "математика + русский + (информатика или обществознание)",
      "egeFits": true,
      "egeCheckNeeded": true,
      "needsObsh": false,
      "budget": 15,
      "quota": 4,
      "realEge": 11,
      "paid": 85,
      "prokhBudget": 277,
      "prokhBudgetApprox": false,
      "priceYear": 381400,
      "filters": ["business"],
      "starAIDS": 2,
      "starBusiness": 5,
      "profileLabel": "бизнес+IT",
      "unavailable": false,
      "source": "spbu.ru, официальный ресёрч в чате, 2025"
    },
    {
      "vuz": "ВШЭ СПб",
      "faculty": "Школа физ.-мат. и комп. наук",
      "name": "Прикладной анализ данных и искусственный интеллект",
      "code": "01.03.02",
      "city": "Санкт-Петербург",
      "campus": "центр",
      "campusFar": false,
      "url": "https://spb.hse.ru/ba/dataanalytics/",
      "urlVerified": false,
      "egeSubjects": "математика + информатика + русский",
      "egeFits": true,
      "needsObsh": false,
      "budget": 30,
      "quota": 17,
      "realEge": 13,
      "paid": 15,
      "prokhBudget": 288,
      "prokhBudgetApprox": false,
      "priceYear": 610000,
      "filters": ["ai", "ds"],
      "starAIDS": 5,
      "starBusiness": 2,
      "profileLabel": "DS + ИИ",
      "unavailable": false,
      "source": "spb.hse.ru/ba/statistics2025, официально подтверждено фетчем, 2025"
    },
    {
      "vuz": "ВШЭ СПб",
      "faculty": "Школа физ.-мат. и комп. наук",
      "name": "Прикладная математика и информатика",
      "code": "01.03.02",
      "city": "Санкт-Петербург",
      "campus": "центр",
      "campusFar": false,
      "url": "https://spb.hse.ru/ba/ami/",
      "urlVerified": false,
      "egeSubjects": "математика + информатика + русский",
      "egeFits": true,
      "needsObsh": false,
      "budget": 30,
      "quota": 6,
      "realEge": 24,
      "paid": 10,
      "prokhBudget": 289,
      "prokhBudgetApprox": false,
      "priceYear": 610000,
      "filters": ["ai", "it"],
      "starAIDS": 4,
      "starBusiness": 1,
      "profileLabel": "ПМИ",
      "unavailable": false,
      "source": "spb.hse.ru/ba/statistics2025, официально подтверждено фетчем, 2025"
    },
    {
      "vuz": "ВШЭ СПб",
      "faculty": "Школа физ.-мат. и комп. наук",
      "name": "Компьютерные технологии, системы и сети",
      "code": "09.03.01",
      "city": "Санкт-Петербург",
      "campus": "центр",
      "campusFar": false,
      "url": "https://spb.hse.ru/ba/ctsn/",
      "urlVerified": false,
      "egeSubjects": "математика + информатика + русский",
      "egeFits": true,
      "needsObsh": false,
      "budget": 13,
      "paid": null,
      "prokhBudget": 278,
      "prokhBudgetApprox": false,
      "priceYear": 610000,
      "filters": ["it"],
      "starAIDS": 3,
      "starBusiness": 1,
      "profileLabel": "чистый IT",
      "unavailable": false,
      "source": "Gemini-отчёт, свериться на spb.hse.ru, 2025"
    },
    {
      "vuz": "ВШЭ СПб",
      "faculty": "Санкт-Петербургская школа экономики и менеджмента",
      "name": "Бизнес-информатика",
      "code": "38.03.05",
      "city": "Санкт-Петербург",
      "campus": "центр",
      "campusFar": false,
      "url": "https://spb.hse.ru/ba/bi/",
      "urlVerified": false,
      "egeSubjects": "математика + русский + (информатика или обществознание)",
      "egeFits": true,
      "needsObsh": false,
      "budget": 25,
      "quota": 5,
      "realEge": 20,
      "paid": 17,
      "prokhBudget": 277,
      "prokhBudgetApprox": false,
      "priceYear": 600000,
      "filters": ["business"],
      "starAIDS": 2,
      "starBusiness": 5,
      "profileLabel": "бизнес+IT",
      "unavailable": false,
      "source": "spb.hse.ru/ba/statistics2025, официально подтверждено фетчем, 2025"
    },
    {
      "vuz": "ВШЭ Москва",
      "faculty": "ФКН",
      "name": "Прикладная математика и информатика",
      "code": "01.03.02",
      "city": "Москва",
      "campus": "Покровский б-р, 11 · центр",
      "campusFar": false,
      "url": "https://cs.hse.ru/",
      "urlVerified": false,
      "egeSubjects": "математика + информатика/физика + русский",
      "egeFits": true,
      "needsObsh": false,
      "budgetOnlyBVI": true,
      "prokhBudgetNote": "практически весь бюджет — БВИ/олимпиадники, общий конкурс почти отсутствует",
      "priceYear": 770000,
      "filters": ["ai", "ds", "it"],
      "starAIDS": 5,
      "starBusiness": 1,
      "profileLabel": "флагман ФКН",
      "unavailable": false,
      "source": "внутренний ресёрч чата, требует проверки конкурсных списков"
    },
    {
      "vuz": "ВШЭ Москва",
      "faculty": "МИЭМ",
      "name": "Информатика и вычислительная техника",
      "code": "09.03.01",
      "city": "Москва",
      "campus": "ул. Таллинская · не центр",
      "campusFar": false,
      "url": "https://miem.hse.ru/",
      "urlVerified": false,
      "egeSubjects": "математика + информатика/физика + русский",
      "egeFits": true,
      "needsObsh": false,
      "budget": null,
      "prokhBudget": 281,
      "prokhBudgetApprox": true,
      "priceYear": 600000,
      "filters": ["it"],
      "starAIDS": 3,
      "starBusiness": 1,
      "profileLabel": "IT",
      "unavailable": false,
      "source": "внутренний ресёрч чата, 2025, оценка"
    },
    {
      "vuz": "СПбПУ",
      "faculty": "ФизМех",
      "name": "Прикладная математика и информатика: Математическое моделирование и ИИ",
      "code": "01.03.02",
      "city": "Санкт-Петербург",
      "campus": "Политехническая ул.",
      "campusFar": false,
      "url": "https://www.spbstu.ru/abit/bachelor/institutes/physics-and-mechanics-institute/",
      "urlVerified": false,
      "egeSubjects": "математика + (физика или информатика) + русский",
      "egeFits": true,
      "needsObsh": false,
      "budget": 80,
      "quota": 20,
      "realEge": 60,
      "paid": 25,
      "prokhBudget": 271,
      "prokhBudgetApprox": false,
      "prokhPaid": 202,
      "priceYear": 250000,
      "filters": ["ai"],
      "starAIDS": 4,
      "starBusiness": 1,
      "profileLabel": "ИИ / матмоделирование",
      "unavailable": false,
      "source": "официальный PDF spbstu.ru/upload/sveden/competition2025.pdf, фетч подтверждён в чате, 2025. ⚠ Gemini даёт 27 мест / 274 балла — расхождение, вероятно другая подгруппа внутри направления, проверить на сайте"
    },
    {
      "vuz": "СПбПУ",
      "faculty": "ИКНК",
      "name": "Программная инженерия",
      "code": "09.03.04",
      "city": "Санкт-Петербург",
      "campus": "Политехническая ул.",
      "campusFar": false,
      "url": "https://www.spbstu.ru/abit/bachelor/institutes/institute-of-computer-science-and-technology/",
      "urlVerified": false,
      "egeSubjects": "математика + (физика или информатика) + русский",
      "egeFits": true,
      "needsObsh": false,
      "budget": 108,
      "quota": 27,
      "realEge": 81,
      "paid": null,
      "prokhBudget": 284,
      "prokhBudgetApprox": false,
      "prokhPaid": 189,
      "priceYear": 265000,
      "filters": ["it"],
      "starAIDS": 3,
      "starBusiness": 1,
      "profileLabel": "IT флагман Политеха",
      "unavailable": false,
      "source": "официальный PDF spbstu.ru, фетч подтверждён, 2025"
    },
    {
      "vuz": "СПбПУ",
      "faculty": "ИКНК",
      "name": "Информационные системы и технологии",
      "code": "09.03.02",
      "city": "Санкт-Петербург",
      "campus": "Политехническая ул.",
      "campusFar": false,
      "url": "https://www.spbstu.ru/abit/bachelor/institutes/institute-of-computer-science-and-technology/",
      "urlVerified": false,
      "egeSubjects": "математика + (физика или информатика) + русский",
      "egeFits": true,
      "needsObsh": false,
      "budget": 48,
      "quota": 12,
      "realEge": 36,
      "paid": null,
      "prokhBudget": 267,
      "prokhBudgetApprox": false,
      "prokhPaid": 154,
      "priceYear": 265000,
      "filters": ["it"],
      "starAIDS": 3,
      "starBusiness": 1,
      "profileLabel": "IT",
      "unavailable": false,
      "source": "официальный PDF spbstu.ru, фетч подтверждён, 2025. ⚠ Gemini даёт 40 мест / 253 балла — расхождение, беру свою цифру из PDF"
    },
    {
      "vuz": "СПбПУ",
      "faculty": "ИПМЭиТ",
      "name": "Бизнес-информатика",
      "code": "38.03.05",
      "city": "Санкт-Петербург",
      "campus": "Политехническая ул.",
      "campusFar": false,
      "url": "https://ipmet.spbstu.ru/",
      "urlVerified": false,
      "egeSubjects": "математика + русский + (информатика или обществознание)",
      "egeFits": true,
      "egeCheckNeeded": true,
      "budget": 50,
      "quota": 13,
      "realEge": 37,
      "paid": 30,
      "prokhBudget": 270,
      "prokhBudgetApprox": false,
      "prokhPaid": 202,
      "priceYear": 302000,
      "filters": ["business"],
      "starAIDS": 2,
      "starBusiness": 5,
      "profileLabel": "бизнес+IT",
      "unavailable": false,
      "source": "официальный PDF spbstu.ru, фетч подтверждён, 2025"
    },
    {
      "vuz": "ЛЭТИ",
      "faculty": "ФКТИ",
      "name": "Системы искусственного интеллекта",
      "code": "01.03.02",
      "city": "Санкт-Петербург",
      "campus": "Петроградская сторона",
      "campusFar": false,
      "url": "https://etu.ru/",
      "urlVerified": false,
      "egeSubjects": "математика + (физика или информатика) + русский",
      "egeFits": true,
      "needsObsh": false,
      "prokhBudget": 245,
      "prokhBudgetApprox": true,
      "priceYear": 142000,
      "filters": ["ai"],
      "starAIDS": 4,
      "starBusiness": 1,
      "profileLabel": "ИИ",
      "unavailable": false,
      "source": "внутренний ресёрч чата, оценка, 2025"
    },
    {
      "vuz": "ЛЭТИ",
      "faculty": "ФКТИ",
      "name": "Программная инженерия",
      "code": "09.03.04",
      "city": "Санкт-Петербург",
      "campus": "Петроградская сторона",
      "campusFar": false,
      "url": "https://etu.ru/",
      "urlVerified": false,
      "egeSubjects": "математика + (физика или информатика) + русский",
      "egeFits": true,
      "needsObsh": false,
      "budget": 68,
      "prokhBudget": 271,
      "prokhBudgetApprox": true,
      "prokhBudgetNote": "цифра из Gemini-отчёта, не перепроверена мной лично — сверить",
      "priceYear": 142000,
      "filters": ["it"],
      "starAIDS": 3,
      "starBusiness": 1,
      "profileLabel": "IT",
      "unavailable": false,
      "source": "Gemini-отчёт, требует проверки"
    },
    {
      "vuz": "СПбГЭУ",
      "faculty": "ФИПМ",
      "name": "Прикладная математика и информатика: в экономике и управлении",
      "code": "01.03.02",
      "city": "Санкт-Петербург",
      "campus": "канал Грибоедова · центр",
      "campusFar": false,
      "url": "https://abit.unecon.ru/informatika",
      "urlVerified": false,
      "egeSubjects": "математика + (физика или информатика) + русский",
      "egeFits": true,
      "needsObsh": false,
      "budget": 86,
      "quota": 21,
      "realEge": 65,
      "paid": 35,
      "prokhBudget": 241,
      "prokhBudgetApprox": false,
      "prokhPaid": 151,
      "priceYear": 304000,
      "filters": ["ds", "business"],
      "starAIDS": 3,
      "starBusiness": 3,
      "profileLabel": "DS + экономика",
      "unavailable": false,
      "source": "официальный PDF unecon.ru/wp-content/uploads/2025/09/itogi-pk-2025.pdf, фетч подтверждён, 2025"
    },
    {
      "vuz": "СПбГЭУ",
      "faculty": "Факультет бизнес-информатики",
      "name": "Бизнес-информатика: Деловая аналитика",
      "code": "38.03.05",
      "city": "Санкт-Петербург",
      "campus": "центр",
      "campusFar": false,
      "url": "https://abit.unecon.ru/biznes-informatika",
      "urlVerified": true,
      "egeSubjects": "математика + русский + (информатика или обществознание)",
      "egeFits": true,
      "egeCheckNeeded": true,
      "budget": 5,
      "paid": 114,
      "prokhBudget": 284,
      "prokhBudgetApprox": false,
      "prokhBudgetNote": "⚠ КОНФЛИКТ ИСТОЧНИКОВ: Gemini заявил проходной 115 (явная ошибка/перепутана программа). Беру 284 из ОФИЦИАЛЬНОГО PDF итогов приёма СПбГЭУ-2025, который лично проверял фетчем в этом чате. НЕ используй цифру 115.",
      "priceYear": 304000,
      "filters": ["business"],
      "starAIDS": 1,
      "starBusiness": 5,
      "profileLabel": "бизнес+IT",
      "unavailable": false,
      "source": "официальный PDF unecon.ru/wp-content/uploads/2025/09/itogi-pk-2025.pdf, фетч подтверждён, 2025"
    },
    {
      "vuz": "МГТУ им. Баумана",
      "faculty": "не указан",
      "name": "Информатика и вычислительная техника",
      "code": "09.03.01",
      "city": "Москва",
      "campus": "2-я Бауманская ул.",
      "campusFar": false,
      "url": "https://bmstu.ru/",
      "urlVerified": false,
      "egeSubjects": "математика + физика/информатика + русский",
      "egeFits": true,
      "needsObsh": false,
      "prokhBudget": 289,
      "prokhBudgetApprox": true,
      "prokhBudgetNote": "цифра из Gemini-отчёта, не перепроверена мной лично — сверить обязательно",
      "priceYear": null,
      "filters": ["it"],
      "starAIDS": 3,
      "starBusiness": 1,
      "profileLabel": "IT инженерия",
      "unavailable": false,
      "source": "Gemini-отчёт, требует проверки на bmstu.ru"
    },
    {
      "vuz": "МГТУ им. Баумана",
      "faculty": "не указан",
      "name": "Математика и компьютерные науки",
      "code": "02.03.01",
      "city": "Москва",
      "campus": "2-я Бауманская ул.",
      "campusFar": false,
      "url": "https://bmstu.ru/",
      "urlVerified": false,
      "egeSubjects": "математика + физика/информатика + русский",
      "egeFits": true,
      "needsObsh": false,
      "prokhBudget": 285,
      "prokhBudgetApprox": true,
      "prokhBudgetNote": "цифра из Gemini-отчёта, не перепроверена мной лично — сверить обязательно",
      "priceYear": null,
      "filters": ["ai", "ds"],
      "starAIDS": 4,
      "starBusiness": 1,
      "profileLabel": "ИИ / математика",
      "unavailable": false,
      "source": "Gemini-отчёт, требует проверки на bmstu.ru"
    }
  ]
};
